### ISSUE TITLE
Error: This is not a DSI rom

### ISSUE THREAD

**Issue by lividhen** [JeffRuLz/TMFH#10]
I just dumped pokemon white 2 from my cart, and when i try to install to the HayaCFW dsi menu it says Error: This is not a DSI rom. I can install TMFH just fine, but it wont work with pokemon, or any other games. I dumped them all with godmode9i.

**Comment by lividhen** [comment]
oh, derp. need to use a forewarder.

**Comment by JeffRuLz** [comment]
Just to clarify for anyone reading this in the future: TMFH only works with DSiWare roms, it does not work with DSi enhanced cartridge games.
