### ISSUE TITLE
DSi free block number is off

### ISSUE THREAD

**Issue by ederenzi78** [JeffRuLz/TMFH#3]
Hi,
It's a really useful app but can you improve the calculation of free DSi NAND space? At the moment it seems off by a large amount and of course if NAND is full the DSi can't be booted (it is necessary to enter Unlaunch filemanager, run GodMode9i and move/delete applications).
Thanks

**Comment by JeffRuLz** [comment]
This is a known issue. I was unable to figure out how to access nand information.
I'll need to experiment more, or wait until someone who knows what they're doing contacts me.

**Comment by ederenzi78** [comment]
Closed with 0.70 version
