### ISSUE TITLE
"00000000.app failed not a directory" if 00030004 folder it isn't present

### ISSUE THREAD

**Issue by Reual4412** [JeffRuLz/TMFH#4]
On latest release it seems that installing apps as a non system title completely fails. Is there something I'm missing or not understanding? I tried installing tmfh for example onto the dsi as a non system title and that fails. I've also tried that 3ds site dump of both a nds and cia decrypted format for mini's march, and installing it as a non system gives the same error. Installing as system titles work fine for all of them.

**Comment by JeffRuLz** [comment]
Are you still having this problem?

**Comment by Reual4412** [comment]
The issue stemmed from the folder not existing, specifically 00030004. If it is created manually or is present the application works fine with no problems. I closed it as the problem I described is not accurate to what the problem actually was (after I figured out it was talking about 00030004 as a folder not existing. Changing title and reopening it)

**Comment by JeffRuLz** [comment]
I see. If Hiya was setup correctly, users should already have a "title" and "00030004" folder. TMFH was working on that assumption but I can have it make those folders if they're not present.

**Comment by JeffRuLz** [comment]
Updated current source and release with this fixed. This will be a silent update because it's an avoidable problem.

**Comment by Reual4412** [comment]
Ok
