### ISSUE TITLE
extern declaration of top and bottom screen in main.h to avoid duplicate symbol link error

### ISSUE THREAD

**Issue by jackokring** [JeffRuLz/TMFH#8]
Using the devkitPro I downloaded today it needs the two declarations on line 13 and 14 of main.h to be external to avoid many linking errors of duplicate symbols, as the code as it stands makes the variables for each .o file. main.c can then have the non `extern` paste just above the enum, after the include lines.

**Comment by JeffRuLz** [comment]
Thanks for the heads-up!
Fixed in e74700db9eba149cf8b5fd0ddc48a9b51c14a34c
