### ISSUE TITLE
When I install a file it doesn't go to the main menu.

### ISSUE THREAD

**Issue by ghost** [JeffRuLz/TMFH#9]

**Comment by JeffRuLz** [comment]
1. How are you running TMFH? From Twilightmenu?
2. Are you sure you are looking at your HiyaCFW menu?

**Comment by ghost** [comment]
Twilightmenu.
I didn't install HiyaCFW, maybe that's the issue?

**Comment by JeffRuLz** [comment]
Yeah, it only works with HiyaCFW. (It's in the name, lol)
